### ISSUE TITLE
Powerline symbols?

### ISSUE THREAD

**Issue by symgryph** [hckiang/font-new-heterodox-mono#2]
I LOVE the font. Could we add powerline symbols for fancy shells like fish that support powerline symbols? I would be willing to test.

**Comment by hckiang** [comment]
Happy to hear you like it. But I don't think it is a good idea to include powerline or other trendy "private-use-area icons" in the releases - nor is this a common practice in other major fonts because cramming an entire icon pack into a monospaced font tend to break the monospace model among other things unless the icons are tailor-made. That said, it is fairly easy to make a Powerline version yourself and here's how to do it:

```
git clone https://github.com/ryanoasis/nerd-fonts
cd nerd-fonts
./font-patcher --powerline /path/to/your/NewHeterodoxMono-Book.otf
```

After this you should see a new otf file in the same folder. I myself am not a big fan of powerline, but the license says that you are welcome to fork the repo and maintain a powerline version if you like the font, provided you rename your version; say, it's perfectly okay to renaming it to "New Heterodox Mono Powerline".

Though, instead of powerline, implementing the [good old box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) is on my list. :)
